### ISSUE TITLE
Scan #platops-help For Similar Tickets Prior to Raising

### ISSUE THREAD

**Issue by ssian2** [hmcts/slack-help-bot#162]
### What would you like to change?

Green Squad encounter a significant number of duplicate tikets for known issues that could easily be cut down if people opted to check `#platops-help` or `#cloud-native-announce` prior to raising their ticket like the workflow asks them. Implement code to check `#platops-help` for them.

This code should look for tickets raised in the last few (three?) days in the same project and environment with similar keywords in the ticket descriptor and then alert the user raising the form if any are found.

**Comment by timja** [comment]
This is done
