### ISSUE TITLE
Rework Documentation Gathering

### ISSUE THREAD

**Issue by ssian2** [hmcts/slack-help-bot#164]
### What would you like to change?

SlackBot currently asks the individual closing a ticket to briefly document the steps taken to resolve it. The current implementation is entirely optional and takes too long to complete, leading to few instances of documentation that are not as helpful as they could be.

The current documentation modal presents three text boxes asking the user where what and how they resolved the ticket. Usually only one of these fields provides any useful information. Rework the documentation gathering step to include a single drop-down menu asking the user to categorise the issue and another **optional** comment box asking the user to briefly describe what they did. Closing the modal without selecting an option from the drop-down should not mark the ticket as 'resolved'.

Potential categories for ticket resolution:

- User error
- Lack of documentation
- Lack of access
- etc.

**Comment by willwatters** [comment]
Updated the documentation modal when resolving tickets:

- Removed the existing three text boxes.
- Created a mandatory drop down menu to allow the user to categorise the issue (note this drop down list can be extended):

Infrastructure issue,
Lack of documentation,
Lack of access,
Other issue,
Performance issue,
Security issue,
User error.

- Created an optional comment box asking the user to describe what they did.
- Closing the modal without without selecting an option from the drop-down menu will not mark the ticket as resolved.
- When the user enters text in the comment box the instructions disappear - the instructions have been added on a new line before the comment box.
- Enhanced the interface by removing some unnecessary icons (i.e. the pencil icon for '')

Branch: https://github.com/hmcts/slack-help-bot/pull/new/feature/DTSPO-Hackathon-Will-Watters

**Comment by willwatters** [comment]
PR approved, merged and run via pipeline - https://github.com/hmcts/slack-help-bot/pull/175

Changes tested and now live and communicated to Platform-Operations Slack channel.
