### ISSUE TITLE
Simplify Ticket Raising Form

### ISSUE THREAD

**Issue by ssian2** [hmcts/slack-help-bot#165]
### What would you like to change?

The SlackBot ticket raising form asks the user for all the information needed in the ticket in a single modal. This can not only be overwhenming but is also very inconvenient as it makes the rest of the user's slack inaccessible as if they at any point close the modal, they lose all the information they entered into it, forcing them to re-enter everything.

Rework the ticket raising form to include several smaller modals that can help atomise the information. Additionally, include edit buttons on the messages sent from SackBot so the user can ammend the data they've already entered. The information to raise the ticket will then be collected from the messages SlackBot sent the user and passed into the regular ticket raising routine like normal.

**Comment by timja** [comment]
I think resolved enough now, a few fields have been removed and AI is now auto suggesting answers and there's some pagination
