### ISSUE TITLE
Document gathering to be added to Jira ticket

### ISSUE THREAD

**Issue by willwatters** [hmcts/slack-help-bot#172]
When closing tickets there is a documentation gathering requirement, which is not added to the associated Jira ticket.

The documentation gathering contents should be added as a comment in the associated Jira ticket and also as a label.

**Comment by timja** [comment]
you planning to get that merged in @willwatters ?

**Comment by willwatters** [comment]
@timja  I can PR this branch, which also includes the removal of the existing three resolution text boxes (Where, What and How) that is replaced with the drop down menu and optional text box.  However, we would need a finalised list for the drop down menu before merging.  This currently has:

Infrastructure issue
Lack of documentation
Lack of access
Other issue
Performance issue
Security issue
User error

Is there a finalised menu list that can be used?

**Comment by timja** [comment]
better to get it in, it's easy to change categories, don't worry about a final list

**Comment by willwatters** [comment]
PR approved, merged and run via pipeline - https://github.com/hmcts/slack-help-bot/pull/175

Changes tested and now live and communicated to Platform-Operations Slack channel.
